# auto.module

module

use drive_train

use servo as latch_servo 1 min: 0 max: 60deg

use spinner_motor


subroutine start
    latch_servo.set_max
    cycle.delay 2
    latch_servo.set_min

    drive_train.skid_drive.move 50in

    spinner_motor.set_power 20%
    cycle.delay 2
    spinner_motor.set_power 0

    drive_train.skid_drive.move -20in
    drive_train.skid_drive.turn 20deg
    drive_train.skid_drive.move -50in
    return


subroutine stop
    spinner_motor.set_power 0
    drive_train.skid_drive.stop
    return
