#!/bin/sh

set -e

version=`sed -n "/ *version='[0-9]*\.[0-9]*\.\(.*\)',/s//\1/p" setup.py`
next_version=`expr $version + 1`

echo version $version
echo next_version $next_version

sed -i "/ *version='/s/\.$version'/.$next_version'/" setup.py
sed -i "/__version__ = '/s/\.$version'/.$next_version'/" robot_brains/__init__.py

rm -r build dist

python setup.py sdist bdist_wheel

twine upload dist/*
