# producer.module

# use iter_types element_type
# use producer iter_types p_next p_done
#
# function my_producer returning iter_types.p_config_t
#     <init code>
#     goto return_label producer.p_config  # I'm still running...
#
#   label p_next
#     <figure out next element>
#     goto producer.c_yield next_element
#     done
#     goto producer.c_done
#
#   subroutine p_done
#     done with: my_producer
#     return

module iter_types p_next p_done

var p_next   is iter_types.p_next_t
var p_done   is iter_types.p_done_t
var c_yield  is iter_types.c_yield_t
var c_done   is iter_types.c_done_t
var c_config is iter_types.c_config_t


subroutine p_config ?c_yield: c_yield ?c_done: c_done ?c_config: c_config
    ==================================================
    | YN | got? c_config:
    ==================================================
    | X  | c_config p_next: p_next p_done: p_done
    |  X | return
    ==================================================

