# builtins module is included by all opmodes!
#
# All names within this modules are available to all modules!

module

use cycle

type label_t is label
type label_l_t is label taking label_t

type p_config_t is subroutine taking ?c_yield: label_l_t ?c_done: label_t
                                  -> ?c_config: c_config_t

type c_config_t is subroutine taking ?p_next: label_t ?p_done: subr_t
                                  -> ?p_config: p_config_t

type subr_t is subroutine

# FIX: temporary
var isAlive? is boolean
var isStarted? is boolean


function get_subroutines_by_name name$ returning p_config_t
  goto return_label p_config

  subroutine p_config ?c_yield: c_yield ?c_done: c_done ?c_config: c_config
    var c_yield is label_l_t
    var c_done is label
    var c_config is c_config_t
    # FIX: how to make this optional?
    c_config p_next: next_routine next_routine: p_done
    set imodule_index to: 0
    set ilabel_index to: 0
    return

  label next_module
    ======================================================================
    | YN | imodule_index < {iget_num_modules}
    ======================================================================
    | X  | set ilabel_index to: 0
    |    | goto next_routine
    |  X | done with: get_subroutine_by_name
    |    | goto c_done
    ======================================================================

  subroutine p_done
    done with: get_subroutines_by_name
    return

  label next_routine
    ======================================================================
    | YN | ilabel_index < {iget_num_labels imodule_index}
    ======================================================================
    | X  | continue
    |  X | goto next_module
    ======================================================================

    ======================================================================
    | YN | {get_label_name$ imodule_index ilabel_index} == name$
    ======================================================================
    | X  | set i to: ilabel_index
    |    | ilabel_index += 1
    |    | c_yield {get_label imodule_index i}
    |  X | ilabel_index += 1
    |    | goto next_routine
    ======================================================================


function iget_num_modules
    # FIX
    return 2


function iget_num_labels imodule
    # FIX
    return 4


function get_label_name$ imodule ilabel
    # FIX
    return "bogus"


function get_label imodule ilabel returning label_t
    # FIX
    return "bogus"
