# telemetry.module

module


subroutine report_integer key: key$ value: ivalue
    `printf("%s: %ld\n", ` key$ `, ` ivalue `);`
    return


subroutine report_float key: key$ value: value
    # 4 digits are printed in engineering notation.
    # numbers less than 1e-6 are printed as 0.0.
    =======================================================
    | YN | (abs value) < 1e-6
    =======================================================
    | X  | `printf("%s: 0.0\n", ` key$ `);`
    |    | return
    |  X | goto non_zero
    =======================================================

  label non_zero
    set flog to: (`log10(` (abs value) `) + 0.000022`)
    set eng to: (`floor(` (flog / 3.0) `) * 3.0`)
    set adj_value to: (value / `exp10(` eng `)`)
    =========================================================
    | YN | eng == 0
    =========================================================
    | X  | `printf("%s: %.4f\n", ` key$ `, ` adj_value `);`
    |    | return
    |  X | `printf("%s: %.4fe%.0f\n", ` key$ `, ` adj_value `, ` eng `);`
    |    | return
    =========================================================


subroutine report_string key: key$ value: value$
    `printf("%s: %s\n", ` key$ `, ` value$ `);`
    return
