# motor.module

module ichannel ?reversed:


subroutine init
    ===============================================================
    | YN | got? module.reversed:
    ===============================================================
    | X  | set_reversed to: true?
    |  X | return
    ===============================================================


subroutine set_reversed to: reversed?
    return


subroutine set_power percent
    return


function position
    return 44
