module autonomous

use drive_train

use latch_servo min: 0 max: 60deg

use spinner_motor


subroutine start
    latch_servo.set_max
    delay 2
    latch_servo.set_min

    drive = drive_train.skid_drive
    drive.move 50in

    spinner_motor.set_power 20%
    delay 2
    spinner_motor.set_power 0

    drive.move -20in
    drive.turn 20deg
    drive.move -50in


subroutine stop
    spinner_motor.set_power 0
    drive_train.skid_drive.stop
